apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneup
  namespace: oneup
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_user_agent ~* (Wappalyzer|Curl|feroxbuster)) {
        return 403;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - oneup.az.lhgroup.de
      secretName: oneup-tls-secret
  rules:
    - host: oneup.az.lhgroup.de
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: oneup
                port:
                  number: 8000