apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pma
  name: tls-pma-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "http-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
    - host: oneup.az.lhgroup.de
      http:
        paths:
          - path: /pma(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: pma
                port:
                  number: 80
  tls:
    - hosts:
        - oneup.az.lhgroup.de
      secretName: oneup-tls-secret
