apiVersion: v1
kind: ConfigMap
metadata:
  namespace: oneup
  name: oneup-env
  labels:
    app: oneup
data:
  APP_NAME: "OneUp"
  APP_ENV: "production"
  CURL_VERIFY: "false"
  APP_DEBUG: "false"
  DEBUGBAR_ENABLED: "false"
  APP_URL: "https://oneup.az.lhgroup.de"
  RATE_LIMIT_API: "60"
  LOG_CHANNEL: "db"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "info"
  DB_CONNECTION: "mysql"
  DB_HOST: "masql-lhg-sm-giti-p01.mariadb.database.azure.com"
  DB_PORT: "3306"
  DB_DATABASE: "oneup_prod"
  DB_USERNAME: "oneup_admin"
  SESSION_CONNECTION: "default"
  BROADCAST_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  REDIS_HOST: "redis-master.oneup-redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_READ_TIMEOUT: "10"
  REDIS_TIMEOUT: "5"
  REDIS_RETRY_INTERVAL: "100"
  REDIS_PERSISTENT: "true"
  REDIS_CLUSTER: "redis"
  REDIS_DB: "0"
  REDIS_CACHE_DB: "1"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "30"
  SESSION_SECURE_COOKIE: "true"
  SESSION_COOKIE: "oneup_session"
  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.office365.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "oneup@dlh.de"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "oneup@dlh.de"
  MAIL_FROM_NAME: "Lufthansa-Group Cloud OneUp"
  SNOW_CLIENT_URI: "https://lhgroup.service-now.com"
  SNOW_CLIENT_ID: "pcifirewall.interface"
  ARM_CACHE_EXPIRE: "540"
  PDNS_CHUNK_ZONES: "200"
  PDNS_CHUNK_RECORDS: "200"
  PDNS_QUEUE_NAME: "pdns"
  PRUNE_BATCHES_HOURS: "10"
  PRUNE_BATCHES_CANCELLED: "10"
  PRUNE_BATCHES_UNFINISHED: "10"
  PRUNE_FAILED_HOURS: "10"
  TELESCOPE_JOB_ENTRY: "false"
  TELESCOPE_EVENT_ENTRY: "false"
  TELESCOPE_BATCH_ENTRY: "false"
  TELESCOPE_BATCH_QUERY: "false"
  TELESCOPE_BATCH_REDIS: "false"
  CHUNK_DISMISS_RISKY_USERS: "1"
  DISMISS_RISKY_USERS: "true"
  APACHE_RUN_USER: "www-data"
  APACHE_RUN_GROUP: "www-data"
  apache: |
    <VirtualHost *:8000>
      DocumentRoot /var/www/html/public

      <Directory "/">
        AllowOverride all
        Require all granted
      </Directory>

      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
