version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            AZURE_CLIENT_ID: '${AZURE_CLIENT_ID}'
            AZURE_CLIENT_SECRET: '${AZURE_CLIENT_SECRET}'
            AZURE_TENANT: '${AZURE_TENANT}'
            AZURE_AD_CLIENT_ID: '${AZURE_CLIENT_ID}'
            AZURE_AD_CLIENT_SECRET: '${AZURE_CLIENT_SECRET}'
            AZURE_AD_TENANT: '${AZURE_TENANT}'
            HUB_SUBSCRIPTION: '${HUB_SUBSCRIPTION}'
            HUB_RESOURCE_GROUP: '${HUB_RESOURCE_GROUP}'
            AZURE_TEST_TENANT: '${AZURE_TEST_TENANT}'
            AZURE_TEST_CLIENT_ID: '${AZURE_TEST_CLIENT_ID}'
            AZURE_TEST_CLIENT_SECRET: '${AZURE_TEST_CLIENT_SECRET}'
            SNOW_PROD_URI: '${SNOW_PROD_URI}'
            SNOW_CLIENT_ID: '${SNOW_CLIENT_ID}'
            SNOW_CLIENT_SECRET: '${SNOW_CLIENT_SECRET}'
            SNOW_UAT_URI: '${SNOW_UAT_URI}'
            SNOW_UAT_CLIENT_ID: '${SNOW_UAT_CLIENT_ID}'
            SNOW_UAT_CLIENT_SECRET: '${SNOW_UAT_CLIENT_SECRET}'
            TELESCOPE_ENABLED: false
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - mysql
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - '${FORWARD_PMA_PORT:-8080}:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 1024M
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
