trigger: none
pool:
  name: LHG-WEUR-GIXI-DEVAGENT-VMSS-01-P
variables:
  - group: oneup-testing-envs

stages:
- stage: Build
  dependsOn: Test
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  variables:
    - template: vars/production.yaml
    - template: vars/global.yaml
  jobs:
    - template: jobs/build.yaml
      parameters:
        registry_name: ${{ variables.registry_name }}
        repository: ${{ variables.repository }}
        tag: $(Build.BuildNumber)
