pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - definitions/*
      - pipeline/*
      - README.md
pool:
  name: LHG-WEUR-GIXI-DEVAGENT-VMSS-01-P
variables:
  - group: oneup-testing-envs

stages:
- stage: Build
  variables:
    - template: vars/production.yaml
    - template: vars/global.yaml
  jobs:
    - template: jobs/build.yaml
      parameters:
        registry_name: ${{ variables.registry_name }}
        repository: ${{ variables.repository }}
        tag: $(Build.BuildNumber)
