trigger: none
pool:
  name: LHG-WEUR-GIXI-DEVAGENT-VMSS-01-P
parameters:
  - name: loglevel
    values:
      - emergency
      - alert
      - critical
      - error
      - warning
      - notice
      - info
      - debug
    default: info
  - name: debug
    values:
      - "true"
      - "false"
    default: "false"

stages:
- stage: Update Debug Mode
  variables:
    - template: vars/production.yaml
  jobs:
    - template: jobs/debug.yaml
      parameters:
        cluster: ${{ variables.cluster }}
        resourceGroup: ${{ variables.resourceGroup }}
        namespace: ${{ variables.namespace }}
        loglevel: ${{ parameters.loglevel }}
        debug: ${{ parameters.debug }}
