apiVersion: batch/v1
kind: CronJob
metadata:
  name: job
  namespace: oneup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name: job
      namespace: oneup
    spec:
      template:
        metadata:
          name: job
          namespace: oneup
        spec:
          containers:
            - name: job
              image: acrlhggixiservicesp.azurecr.io/oneup:latest
              imagePullPolicy: Always
              volumeMounts:
                - name: apache-config
                  mountPath: /etc/apache2/sites-available/
                - name: oneup-storage
                  mountPath: /var/www/html/storage/app/
              envFrom:
              - secretRef:
                  name: oneup-env
              - configMapRef:
                  name: oneup-env
              command:
                - "/bin/sh"
                - "-c"
                - >
                  php artisan config:cache;
                  php artisan schedule:run;
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: agentpool
                        operator: In
                        values:
                          - userpool
          restartPolicy: OnFailure
          volumes:
            - name: apache-config
              configMap:
                name: oneup-env
                items:
                  - key: apache
                    path: 000-default.conf
            - name: oneup-storage
              persistentVolumeClaim:
                claimName: oneup-storage