apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule
  namespace: oneup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name: schedule
      namespace: oneup
    spec:
      template:
        metadata:
          name: schedule
          namespace: oneup
        spec:
          containers:
            - name: schedule
              image: acrlhggixiservicesp.azurecr.io/oneup:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: apache-config
                  mountPath: /etc/apache2/sites-available/
                - name: ssl
                  mountPath: /var/www/html/ssl/
                  readOnly: true
                - name: oneup-storage
                  mountPath: /var/www/html/storage/app/
              envFrom:
              - secretRef:
                  name: oneup-env
              - configMapRef:
                  name: oneup-env
              command:
                - "/bin/sh"
                - "-c"
                - >
                  php artisan optimize:clear;
                  php artisan config:cache;
                  php artisan schedule:run;
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: agentpool
                        operator: In
                        values:
                          - userpool
          restartPolicy: OnFailure
          volumes:
            - name: apache-config
              configMap:
                name: oneup-env
                items:
                  - key: apache
                    path: 000-default.conf
            - name: ssl
              secret:
                secretName: oneup-tls-secret
                items:
                  - key: mysql-attr-ssl-ca
                    path: DigiCertGlobalRootCA.crt.pem
                  - key: mysql-attr-ssl-key
                    path: BaltimoreCyberTrustRoot.crt.pem
            - name: oneup-storage
              persistentVolumeClaim:
                claimName: oneup-storage