apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: oneup
spec:
  replicas: 4
  selector:
    matchLabels:
      app: queue
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue-dns
          image: acrlhggixiservicesp.azurecr.io/oneup:latest
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-c"
            - >
              php artisan config:clear;
              php artisan migrate --force;
              php artisan queue:work --queue=dns --timeout=1800;
          resources:
            requests:
              cpu: "124m"
              memory:  "405Mi"
            limits:
              cpu: "254m"
              memory:  "884Mi"
          volumeMounts:
            - name: apache-config
              mountPath: /etc/apache2/sites-available/
              readOnly: true
            - name: oneup-storage
              mountPath: /var/www/html/storage/app/
          envFrom:
            - secretRef:
                name: oneup-env
            - configMapRef:
                name: oneup-env
          ports:
            - containerPort: 8000
              name: oneup
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - userpool
      volumes:
        - name: apache-config
          configMap:
            name: oneup-env
            items:
              - key: apache
                path: 000-default.conf
        - name: oneup-storage
          persistentVolumeClaim:
            claimName: oneup-storage