apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oneup-storage
  namespace: oneup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
