variables:
  repository: "oneup"
  namespace: "oneup"
  cluster: "AKS-LHG-SM-GIXI-01P"
  resource_group: "rg_lhg_aks_gixi_01_p"
  registry_name: "acrlhggixiservicesp.azurecr.io"
  registry_rg: "RG_LHG_ACR_01_P"
  source_registry: "registry.k8s.io"
  controller_image: "ingress-nginx/controller"
  chart_version: "4.9.0"
  controller_tag: "v1.9.5"
  patch_image: "ingress-nginx/kube-webhook-certgen"
  patch_tag: "v20231011-8b53cabe0"
  defaultbackend_image: "defaultbackend-amd64"
  defaultbackend_tag: "1.5"
  ingress_config: "/definitions/helm/ingress-config.yaml"