variables:
  repository: "oneup"
  namespace: "oneup"
  cluster: "AKS-LHG-SM-GIXI-01P"
  resource_group: "rg_lhg_aks_gixi_01_p"
  registry_name: "acrlhggixiservicesp.azurecr.io"
  registry_rg: "RG_LHG_ACR_01_P"
  source_registry: "k8s.gcr.io"
  chart_version: "4.6.0"
  controller_image: "ingress-nginx/controller"
  controller_tag: "v1.7.0"
  patch_image: "ingress-nginx/kube-webhook-certgen"
  patch_tag: "v20230312-helm-chart-4.5.2-28-g66a760794"
  defaultbackend_image: "defaultbackend-amd64"
  defaultbackend_tag: "1.5"
  ingress_config: "/definitions/helm/ingress-config.yaml"